//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdysseyExt.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OdysseyExt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        internal static byte[] baseModels {
            get {
                object obj = ResourceManager.GetObject("baseModels", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {&quot;CameraArea&quot;:{&quot;P&quot;:{&quot;IsEndNoInterpole&quot;:&quot;Boolean&quot;,&quot;IsStartWhenCollideGround&quot;:&quot;Boolean&quot;,&quot;IsStartWhenInWater&quot;:&quot;Boolean&quot;,&quot;Priority&quot;:&quot;Int32&quot;},&quot;D&quot;:&quot;can contain links SwitchAppear [StageSwitch] TowerCameraAxis [TowerCameraAxis] Rail [RailCameraRailMoveMovie;Rail] SwitchKill [StageSwitch] InnerTowerCameraAxis [InnerTowerCameraAxis] NoDelete_RootArea [CameraArea] TargetLimitArea [CameraTargetLimitArea] Can contain array nodes [SrcUnitLayerList]&quot;},&quot;CameraStopArea&quot;:{&quot;P&quot;:{&quot;Priority&quot;:&quot;Int32&quot;},&quot;D&quot;:&quot;can contain links Swit [stringa troncata]&quot;;.
        /// </summary>
        internal static string OdysseyDB {
            get {
                return ResourceManager.GetString("OdysseyDB", resourceCulture);
            }
        }
    }
}
